// Ampliación SEO del catálogo: 29 playas nuevas + Areacova.
// Las coordenadas se han contrastado con fichas oficiales de Turismo de Galicia
// y, para Cíes/Ons, con el Parque Nacional de las Illas Atlánticas.
// La orientación y el nivel de abrigo son parámetros de modelado de Hoy Toca Playa.
const PLAYAS_EXTRA = [
  {
    nombre: "Praia de Areacova",
    slugFicha: "praia-de-areacova",
    municipio: "Cangas",
    provincia: "Pontevedra",
    lat: 42.287894,
    lon: -8.820833,
    orientacion: "SE",
    anguloAproximado: 140,
    nivelAbrigo: "alto",
    zonaMeteorologica: "aldan",
    destinoMaps: "Praia de Areacova, Aldán, Cangas, Galicia",
    descripcionSEO: "Pequeña playa resguardada de la ría de Aldán, en Cangas.",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Baltar (Portonovo)",
    slugFicha: "praia-de-baltar-portonovo",
    municipio: "Sanxenxo",
    provincia: "Pontevedra",
    lat: 42.398722,
    lon: -8.822528,
    orientacion: "S",
    anguloAproximado: 180,
    nivelAbrigo: "alto",
    zonaMeteorologica: "sanxenxo",
    destinoMaps: "Praia de Baltar, Portonovo, Sanxenxo, Galicia",
    descripcionSEO: "Playa resguardada junto a Portonovo, uno de los arenales urbanos más conocidos de Sanxenxo.",
    tipoOficial: "Playa resguardada",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/recurso/-/detalle/9778/baltar?langId=es_ES"
  },
  {
    nombre: "Praia de Caneliñas (Portonovo)",
    slugFicha: "praia-de-canelinas-portonovo",
    municipio: "Sanxenxo",
    provincia: "Pontevedra",
    lat: 42.391833,
    lon: -8.825833,
    orientacion: "S",
    anguloAproximado: 170,
    nivelAbrigo: "alto",
    zonaMeteorologica: "sanxenxo",
    destinoMaps: "Praia de Caneliñas, Portonovo, Sanxenxo, Galicia",
    descripcionSEO: "Playa resguardada situada en el núcleo de Portonovo, Sanxenxo.",
    tipoOficial: "Playa resguardada",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Areas",
    slugFicha: "praia-de-areas-sanxenxo",
    municipio: "Sanxenxo",
    provincia: "Pontevedra",
    lat: 42.394611,
    lon: -8.778778,
    orientacion: "S",
    anguloAproximado: 190,
    nivelAbrigo: "moderado",
    zonaMeteorologica: "sanxenxo",
    destinoMaps: "Praia de Areas, Sanxenxo, Galicia",
    descripcionSEO: "Amplio arenal de Sanxenxo clasificado como playa abierta.",
    tipoOficial: "Playa abierta",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Paxariñas",
    slugFicha: "praia-de-paxarinas",
    municipio: "Sanxenxo",
    provincia: "Pontevedra",
    lat: 42.391639,
    lon: -8.844056,
    orientacion: "SW",
    anguloAproximado: 220,
    nivelAbrigo: "alto",
    zonaMeteorologica: "sanxenxo",
    destinoMaps: "Praia de Paxariñas, Sanxenxo, Galicia",
    descripcionSEO: "Playa resguardada del litoral de Sanxenxo, entre Portonovo y Montalvo.",
    tipoOficial: "Playa resguardada",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Bascuas",
    slugFicha: "praia-de-bascuas",
    municipio: "Sanxenxo",
    provincia: "Pontevedra",
    lat: 42.404139,
    lon: -8.858139,
    orientacion: "W",
    anguloAproximado: 260,
    nivelAbrigo: "moderado",
    zonaMeteorologica: "sanxenxo",
    destinoMaps: "Praia de Bascuas, Sanxenxo, Galicia",
    descripcionSEO: "Arenal abierto del municipio de Sanxenxo, conocido también por su tradición nudista.",
    tipoOficial: "Playa abierta",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Foxos",
    slugFicha: "praia-de-foxos",
    municipio: "Sanxenxo",
    provincia: "Pontevedra",
    lat: 42.427139,
    lon: -8.873667,
    orientacion: "W",
    anguloAproximado: 270,
    nivelAbrigo: "moderado",
    zonaMeteorologica: "sanxenxo",
    destinoMaps: "Praia de Foxos, Sanxenxo, Galicia",
    descripcionSEO: "Playa abierta de Sanxenxo próxima al entorno de A Lanzada.",
    tipoOficial: "Playa abierta",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Panadeira",
    slugFicha: "praia-de-panadeira",
    municipio: "Sanxenxo",
    provincia: "Pontevedra",
    lat: 42.400722,
    lon: -8.803889,
    orientacion: "S",
    anguloAproximado: 180,
    nivelAbrigo: "muyAlto",
    zonaMeteorologica: "sanxenxo",
    destinoMaps: "Praia de Panadeira, Sanxenxo, Galicia",
    descripcionSEO: "Pequeña playa urbana y resguardada situada en el núcleo de Sanxenxo.",
    tipoOficial: "Playa resguardada",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Melide (Isla de Ons)",
    slugFicha: "praia-de-melide-isla-de-ons",
    municipio: "Bueu",
    provincia: "Pontevedra",
    lat: 42.390083,
    lon: -8.925583,
    orientacion: "E",
    anguloAproximado: 90,
    nivelAbrigo: "alto",
    zonaMeteorologica: "illa_ons",
    destinoMaps: "Praia de Melide, Illa de Ons, Bueu, Galicia",
    descripcionSEO: "Arenal de arena fina de la Isla de Ons, dentro del Parque Nacional de las Illas Atlánticas.",
    tipoOficial: "Playa resguardada",
    composicionOficial: "Arena fina",
    fuenteNombre: "Parque Nacional Marítimo-Terrestre das Illas Atlánticas de Galicia",
    fuenteUrl: "https://illasatlanticas.gal/es/tipo-punto-de-interese/playas"
  },
  {
    nombre: "Area dos Cans (Isla de Ons)",
    slugFicha: "area-dos-cans-isla-de-ons",
    municipio: "Bueu",
    provincia: "Pontevedra",
    lat: 42.374694,
    lon: -8.932889,
    orientacion: "E",
    anguloAproximado: 90,
    nivelAbrigo: "alto",
    zonaMeteorologica: "illa_ons",
    destinoMaps: "Area dos Cans, Illa de Ons, Bueu, Galicia",
    descripcionSEO: "Playa de arena fina en la costa oriental de la Isla de Ons, dentro del Parque Nacional.",
    tipoOficial: "Playa resguardada",
    composicionOficial: "Arena fina",
    fuenteNombre: "Parque Nacional Marítimo-Terrestre das Illas Atlánticas de Galicia",
    fuenteUrl: "https://illasatlanticas.gal/es/tipo-punto-de-interese/playas"
  },
  {
    nombre: "Praia de Canexol (Isla de Ons)",
    slugFicha: "praia-de-canexol-isla-de-ons",
    municipio: "Bueu",
    provincia: "Pontevedra",
    lat: 42.369944,
    lon: -8.934250,
    orientacion: "E",
    anguloAproximado: 90,
    nivelAbrigo: "moderado",
    zonaMeteorologica: "illa_ons",
    destinoMaps: "Praia de Canexol, Illa de Ons, Bueu, Galicia",
    descripcionSEO: "Arenal de arena fina de la Isla de Ons, integrado en el Parque Nacional de las Illas Atlánticas.",
    tipoOficial: "Playa abierta",
    composicionOficial: "Arena fina",
    fuenteNombre: "Parque Nacional Marítimo-Terrestre das Illas Atlánticas de Galicia",
    fuenteUrl: "https://illasatlanticas.gal/es/tipo-punto-de-interese/playas"
  },
  {
    nombre: "Praia das Dornas (Isla de Ons)",
    slugFicha: "praia-das-dornas-isla-de-ons",
    municipio: "Bueu",
    provincia: "Pontevedra",
    lat: 42.377361,
    lon: -8.931472,
    orientacion: "E",
    anguloAproximado: 90,
    nivelAbrigo: "alto",
    zonaMeteorologica: "illa_ons",
    destinoMaps: "Praia das Dornas, Illa de Ons, Bueu, Galicia",
    descripcionSEO: "Pequeño arenal de la Isla de Ons próximo al núcleo y al muelle principal.",
    tipoOficial: "Playa abierta",
    composicionOficial: "Arena gruesa",
    fuenteNombre: "Parque Nacional Marítimo-Terrestre das Illas Atlánticas de Galicia",
    fuenteUrl: "https://illasatlanticas.gal/es/tipo-punto-de-interese/playas"
  },
  {
    nombre: "Praia de Figueiras (Islas Cíes)",
    slugFicha: "praia-de-figueiras-islas-cies",
    municipio: "Vigo",
    provincia: "Pontevedra",
    lat: 42.231056,
    lon: -8.900583,
    orientacion: "E",
    anguloAproximado: 90,
    nivelAbrigo: "moderado",
    zonaMeteorologica: "illas_cies",
    destinoMaps: "Praia de Figueiras, Illas Cíes, Vigo, Galicia",
    descripcionSEO: "Playa de arena fina de las Islas Cíes, dentro del Parque Nacional de las Illas Atlánticas.",
    tipoOficial: "Playa abierta",
    composicionOficial: "Arena fina",
    fuenteNombre: "Parque Nacional Marítimo-Terrestre das Illas Atlánticas de Galicia",
    fuenteUrl: "https://illasatlanticas.gal/es/tipo-punto-de-interese/playas"
  },
  {
    nombre: "Praia de Nosa Señora (Islas Cíes)",
    slugFicha: "praia-de-nosa-senora-islas-cies",
    municipio: "Vigo",
    provincia: "Pontevedra",
    lat: 42.216167,
    lon: -8.902333,
    orientacion: "E",
    anguloAproximado: 90,
    nivelAbrigo: "alto",
    zonaMeteorologica: "illas_cies",
    destinoMaps: "Praia de Nosa Señora, Illas Cíes, Vigo, Galicia",
    descripcionSEO: "Pequeña playa resguardada de arena fina en las Islas Cíes, protegida del viento del norte.",
    tipoOficial: "Playa resguardada",
    composicionOficial: "Arena fina",
    fuenteNombre: "Parque Nacional Marítimo-Terrestre das Illas Atlánticas de Galicia",
    fuenteUrl: "https://illasatlanticas.gal/es/tipo-punto-de-interese/playas"
  },
  {
    nombre: "Praia de Morouzos",
    slugFicha: "praia-de-morouzos",
    municipio: "Ortigueira",
    provincia: "A Coruña",
    lat: 43.703528,
    lon: -7.848333,
    orientacion: "NE",
    anguloAproximado: 45,
    nivelAbrigo: "moderado",
    zonaMeteorologica: "ortigueira",
    destinoMaps: "Praia de Morouzos, Ortigueira, Galicia",
    descripcionSEO: "Gran arenal de la ría de Ortigueira, con más de dos kilómetros de longitud.",
    tipoOficial: "Playa abierta",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/que-visitar/rias-e-praias/ria-de-ortigueira?langId=es_ES"
  },
  {
    nombre: "Praia da Concha (Espasante)",
    slugFicha: "praia-da-concha-espasante",
    municipio: "Ortigueira",
    provincia: "A Coruña",
    lat: 43.719083,
    lon: -7.809667,
    orientacion: "S",
    anguloAproximado: 180,
    nivelAbrigo: "alto",
    zonaMeteorologica: "ortigueira",
    destinoMaps: "Praia da Concha, Espasante, Ortigueira, Galicia",
    descripcionSEO: "Arenal de Espasante, en el municipio de Ortigueira.",
    tipoOficial: "Playa abierta",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia da Basteira",
    slugFicha: "praia-da-basteira",
    municipio: "Cariño",
    provincia: "A Coruña",
    lat: 43.732000,
    lon: -7.871556,
    orientacion: "SE",
    anguloAproximado: 120,
    nivelAbrigo: "alto",
    zonaMeteorologica: "carino",
    destinoMaps: "Praia da Basteira, Cariño, Galicia",
    descripcionSEO: "Playa resguardada situada junto al núcleo de Cariño.",
    tipoOficial: "Playa resguardada",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Vilarrube",
    slugFicha: "praia-de-vilarrube",
    municipio: "Valdoviño",
    provincia: "A Coruña",
    lat: 43.642667,
    lon: -8.072000,
    orientacion: "NE",
    anguloAproximado: 45,
    nivelAbrigo: "alto",
    zonaMeteorologica: "cedeira_valdovino",
    destinoMaps: "Praia de Vilarrube, Valdoviño, Galicia",
    descripcionSEO: "Arenal resguardado de Valdoviño situado en la desembocadura del río das Mestas.",
    tipoOficial: "Playa resguardada",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia A Magdalena (Cedeira)",
    slugFicha: "praia-a-magdalena-cedeira",
    municipio: "Cedeira",
    provincia: "A Coruña",
    lat: 43.659167,
    lon: -8.056917,
    orientacion: "SW",
    anguloAproximado: 220,
    nivelAbrigo: "muyAlto",
    zonaMeteorologica: "cedeira_valdovino",
    destinoMaps: "Praia A Magdalena, Cedeira, Galicia",
    descripcionSEO: "Principal playa urbana de Cedeira, situada en el interior de su ría.",
    tipoOficial: "Playa resguardada",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Esmelle",
    slugFicha: "praia-de-esmelle",
    municipio: "Ferrol",
    provincia: "A Coruña",
    lat: 43.534250,
    lon: -8.295500,
    orientacion: "W",
    anguloAproximado: 280,
    nivelAbrigo: "moderado",
    zonaMeteorologica: "ferrol_oeste",
    destinoMaps: "Praia de Esmelle, Ferrol, Galicia",
    descripcionSEO: "Playa abierta del litoral atlántico de Ferrol.",
    tipoOficial: "Playa abierta",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Ponzos",
    slugFicha: "praia-de-ponzos",
    municipio: "Ferrol",
    provincia: "A Coruña",
    lat: 43.555583,
    lon: -8.271389,
    orientacion: "NW",
    anguloAproximado: 310,
    nivelAbrigo: "moderado",
    zonaMeteorologica: "ferrol_oeste",
    destinoMaps: "Praia de Ponzos, Ferrol, Galicia",
    descripcionSEO: "Gran playa abierta de la costa de Ferrol, expuesta al Atlántico.",
    tipoOficial: "Playa abierta",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Santa Comba",
    slugFicha: "praia-de-santa-comba",
    municipio: "Ferrol",
    provincia: "A Coruña",
    lat: 43.555750,
    lon: -8.291139,
    orientacion: "NW",
    anguloAproximado: 315,
    nivelAbrigo: "moderado",
    zonaMeteorologica: "ferrol_oeste",
    destinoMaps: "Praia de Santa Comba, Ferrol, Galicia",
    descripcionSEO: "Playa abierta y natural del litoral de Ferrol, junto a la ermita de Santa Comba.",
    tipoOficial: "Playa abierta",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Area das Pipas",
    slugFicha: "praia-de-area-das-pipas",
    municipio: "O Grove",
    provincia: "Pontevedra",
    lat: 42.481361,
    lon: -8.893889,
    orientacion: "W",
    anguloAproximado: 270,
    nivelAbrigo: "alto",
    zonaMeteorologica: "o_grove",
    destinoMaps: "Praia de Area das Pipas, O Grove, Galicia",
    descripcionSEO: "Playa resguardada de O Grove, en el entorno de San Vicente y la península grovense.",
    tipoOficial: "Playa resguardada",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Raeiros-Paxareiro",
    slugFicha: "praia-de-raeiros-paxareiro",
    municipio: "O Grove",
    provincia: "Pontevedra",
    lat: 42.461639,
    lon: -8.897583,
    orientacion: "S",
    anguloAproximado: 200,
    nivelAbrigo: "moderado",
    zonaMeteorologica: "o_grove",
    destinoMaps: "Praia de Raeiros, O Grove, Galicia",
    descripcionSEO: "Arenal abierto de O Grove con vistas hacia la ría de Arousa y A Lanzada.",
    tipoOficial: "Playa abierta",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia da Mexilloeira",
    slugFicha: "praia-da-mexilloeira",
    municipio: "O Grove",
    provincia: "Pontevedra",
    lat: 42.474556,
    lon: -8.909250,
    orientacion: "SW",
    anguloAproximado: 230,
    nivelAbrigo: "alto",
    zonaMeteorologica: "o_grove",
    destinoMaps: "Praia da Mexilloeira, O Grove, Galicia",
    descripcionSEO: "Playa resguardada del municipio de O Grove.",
    tipoOficial: "Playa resguardada",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Area de Secada (Illa de Arousa)",
    slugFicha: "praia-de-area-de-secada-illa-de-arousa",
    municipio: "A Illa de Arousa",
    provincia: "Pontevedra",
    lat: 42.567944,
    lon: -8.887083,
    orientacion: "W",
    anguloAproximado: 270,
    nivelAbrigo: "alto",
    zonaMeteorologica: "illa_arousa",
    destinoMaps: "Praia de Area de Secada, A Illa de Arousa, Galicia",
    descripcionSEO: "Playa resguardada en A Illa de Arousa, rodeada por el paisaje de la ría de Arousa.",
    tipoOficial: "Playa resguardada",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia do Bao / Camaxe (Illa de Arousa)",
    slugFicha: "praia-do-bao-camaxe-illa-de-arousa",
    municipio: "A Illa de Arousa",
    provincia: "Pontevedra",
    lat: 42.544361,
    lon: -8.867472,
    orientacion: "SE",
    anguloAproximado: 150,
    nivelAbrigo: "alto",
    zonaMeteorologica: "illa_arousa",
    destinoMaps: "Praia de Camaxe, A Illa de Arousa, Galicia",
    descripcionSEO: "Arenal resguardado de A Illa de Arousa, identificado en la relación 2026 de Banderas Azules como Bao (Camaxe).",
    tipoOficial: "Playa resguardada",
    composicionOficial: "Arena gruesa",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Cabeceira",
    slugFicha: "praia-de-cabeceira",
    municipio: "Poio",
    provincia: "Pontevedra",
    lat: 42.424167,
    lon: -8.683083,
    orientacion: "S",
    anguloAproximado: 180,
    nivelAbrigo: "muyAlto",
    zonaMeteorologica: "poio",
    destinoMaps: "Praia de Cabeceira, Poio, Galicia",
    descripcionSEO: "Playa resguardada de Poio, en el interior de la ría de Pontevedra.",
    tipoOficial: "Playa resguardada",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Xiorto",
    slugFicha: "praia-de-xiorto",
    municipio: "Poio",
    provincia: "Pontevedra",
    lat: 42.402889,
    lon: -8.756639,
    orientacion: "S",
    anguloAproximado: 180,
    nivelAbrigo: "alto",
    zonaMeteorologica: "poio",
    destinoMaps: "Praia de Xiorto, Poio, Galicia",
    descripcionSEO: "Pequeña playa resguardada del municipio de Poio, en la ría de Pontevedra.",
    tipoOficial: "Playa resguardada",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  },
  {
    nombre: "Praia de Bamio",
    slugFicha: "praia-de-bamio",
    municipio: "Vilagarcía de Arousa",
    provincia: "Pontevedra",
    lat: 42.632667,
    lon: -8.761500,
    orientacion: "W",
    anguloAproximado: 270,
    nivelAbrigo: "muyAlto",
    zonaMeteorologica: "vilagarcia",
    destinoMaps: "Praia de Bamio, Vilagarcía de Arousa, Galicia",
    descripcionSEO: "Playa resguardada de Vilagarcía de Arousa situada en el fondo de la ría.",
    tipoOficial: "Playa resguardada",
    fuenteNombre: "Turismo de Galicia",
    fuenteUrl: "https://www.turismo.gal/"
  }
];

if (typeof playas !== "undefined") {
  for (const playaExtra of PLAYAS_EXTRA) {
    const existe = playas.some(playa =>
      playa.nombre === playaExtra.nombre && playa.municipio === playaExtra.municipio
    );
    if (!existe) playas.push({ ...playaExtra });

    if (window.HoyTocaPlayaIndiceFichas) {
      const clave = `${playaExtra.nombre}||${playaExtra.municipio}`;
      const slugIndice = window.HoyTocaPlayaIndiceFichas[clave];
      const incorporada = playas.find(playa =>
        playa.nombre === playaExtra.nombre && playa.municipio === playaExtra.municipio
      );
      if (incorporada) incorporada.slugFicha = slugIndice || incorporada.slugFicha || null;
    }
  }
}
